Allow user to customize the container images to deploy
Up to now, the list of container images was hardcoded and limited to the ceph use case.
With this commit, the user can add images to download/deploy using the USERCUSTOMIZATION class.

Signed-off-by: Florent CARLI <florent.carli@rte-france.com>

diff --git a/srv_fai_config/files/firstboot.sh/SEAPATH_CLUSTER b/srv_fai_config/files/firstboot.sh/SEAPATH_CLUSTER
--- a/srv_fai_config/files/firstboot.sh/SEAPATH_CLUSTER
+++ b/srv_fai_config/files/firstboot.sh/SEAPATH_CLUSTER
@@ -1,10 +1,19 @@
 #!/bin/bash
-for i in quay.io/ceph/ceph:v20.2.0 docker.io/library/registry:2
-do
-    registry=$(echo $i | cut -d'/' -f2)
-    image=$(echo $i | cut -d'/' -f3 | sed s/://g)
-    podman load -i /opt/$registry"_"$image.tgz
-    rm -f /opt/$registry"_"$image.tgz
+# Load all container images from /opt/*.tgz files
+# This is simpler and more robust - no need for a config file
+for tgz_file in /opt/*.tgz; do
+    # Check if file exists (in case /opt is empty)
+    [ -f "$tgz_file" ] || continue
+    
+    # Try to load the image
+    if podman load -i "$tgz_file" >/dev/null 2>&1; then
+        echo "Loaded container image from $tgz_file"
+        rm -f "$tgz_file"
+    else
+        echo "Warning: Failed to load container image from $tgz_file (may not be a valid image file)" >&2
+        # Optionally remove invalid files or keep them for debugging
+        # rm -f "$tgz_file"
+    fi
 done
 systemctl disable firstboot.service
 rm -f /etc/systemd/system/firstboot.service
